# A generic, single database configuration.

[alembic]
# path to migration script
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepended_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value is passed to ZoneInfo()
# leaves the date naive if not set
# timezone =

# max length of characters in file names created by the
# revision command
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a companion .py file to be detected as revisions in the
# revisions/ directory
# sourceless = false

# version location specification; This defaults
# to alembic/versions. Operating systems (e.g. Windows)
# that use semicolons as path separators in environment variables
# can also use semicolons here
version_locations = %(here)s/alembic/versions

# set to 'true' to search source files recursively
# in each version_locations directory
# recursive_version_locations = false

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://user:pass@localhost/dbname


[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root, alembic, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
